# Generated by Django 2.2.4 on 2019-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190903_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
