# Generated by Django 2.2.4 on 2019-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190903_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=1),
        ),
    ]
