# Generated by Django 2.2.4 on 2019-09-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190903_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boards',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')]),
        ),
    ]
