# Generated by Django 2.2.4 on 2019-09-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190904_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
