# Generated by Django 2.2.4 on 2019-09-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190904_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]),
        ),
    ]
