# Generated by Django 2.2.4 on 2019-09-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190904_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
